# Generated by Django 3.2.8 on 2021-10-30 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incapacidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.CharField(choices=[('CC', 'Cédula Ciudadanía'), ('PP', 'Permiso Permanente'), ('CE', 'Cédula Extranjería'), ('TI', 'Tarjeta de identidad')], max_length=200, verbose_name='Tipo Documento')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
                ('cargo', models.CharField(max_length=255, verbose_name='Cargo')),
                ('area', models.CharField(max_length=255, verbose_name='Area')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='DatosIncapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eps', models.CharField(max_length=100, verbose_name='EPS')),
                ('origen', models.CharField(max_length=255, verbose_name='Descripción Enfermedad')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio incapacidad')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin incapacidad')),
                ('dias_incapacidad', models.IntegerField(verbose_name='Días de Incapacidad')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('archivo_inc', models.FileField(default='/media/archivos', upload_to='', verbose_name='Cargue el archivo con la incapacidad')),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Incapacidad',
                'verbose_name_plural': 'Incapacidades',
            },
        ),
    ]
